readerboard.pdf: readerboard.tex common.tex ../firmware/readerboard/fonts.tex ../hardware/matrix64x8_rgb_330_schematic.png ../hardware/matrix64x8_rgb_330_assembly-0.png ../hardware/matrix64x8_rgb_330_assembly-1.png
	pdflatex readerboard

full-build:
	pdflatex readerboard
	pdflatex readerboard
	pdflatex readerboard
